import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import {
  SYNTHETIC_BOOTSTRAP_INTAKE_SNAPSHOT,
  SYNTHETIC_QUALIFICATION_PROFILE_ID,
  SYNTHETIC_QUALIFICATION_PROFILE_VERSION,
  createSyntheticQualificationPreview,
  deriveSyntheticBootstrapIdentities,
} from '@/lib/flow/filingPreparationSyntheticQualification';
import { handleSyntheticBootstrapRequest, type SyntheticBootstrapRouteDependencies } from './route';

const USER='11111111-1111-4111-8111-111111111111';
const AT='2026-08-24T23:50:00.000Z';
let passed=0;
function eq(a:unknown,b:unknown,m:string){assert.deepEqual(a,b,m);passed++;}
function ok(v:unknown,m:string){assert.ok(v,m);passed++;}
function req(body:unknown,auth='Bearer synthetic-owner-token'){return new Request('https://ownerpilot.test/bootstrap',{method:'POST',headers:{authorization:auth,'content-type':'application/json'},body:JSON.stringify(body)});}
async function body(r:Response){return await r.json() as Record<string,unknown>;}
function fake(userId:string,generation:string,at:string):any{const ids=deriveSyntheticBootstrapIdentities(userId,generation);return {syntheticOnly:true,profileId:SYNTHETIC_QUALIFICATION_PROFILE_ID,profileVersion:SYNTHETIC_QUALIFICATION_PROFILE_VERSION,profileBindingId:ids.profileBindingId,riskpathRecordId:ids.riskpathRecordId,e2eRunId:ids.e2eRunId,createdNoticeArtifactId:ids.createdNoticeArtifactId,riskpathInsert:{id:ids.riskpathRecordId,user_id:userId,chat_session_id:null,property_id:null,notice_document_id:null,current_state:'notice_created',captured_payload:structuredClone(SYNTHETIC_BOOTSTRAP_INTAKE_SNAPSHOT),transcript_snapshot:[],transcript_snapshot_at:at,counsel_route_trigger:null,produce_snapshot:{producedAtISO:at,propertyAddress:'100 Synthetic Qualification Avenue',propertyCounty:'Los Angeles',tenantNames:['Synthetic Qualification Tenant One','Synthetic Qualification Tenant Two'],totalAmount:2500,rentPeriods:[{start:'2026-08-01',end:'2026-08-31',amount:2500}],payeeName:'Synthetic Qualification Owner',payeePhone:'5555550100',payeeStreetAddress:'100 Synthetic Qualification Avenue',paymentBranch:'mail_only',signerName:'Synthetic Qualification Owner',signerCapacity:'owner'},created_notice_artifact_id:ids.createdNoticeArtifactId,created_notice_service_date:'2026-12-01',created_notice_generation:generation,created_notice_semantic_binding_id:'created-notice-semantic-binding-v1:synthetic-test',created_notice_finalized_at:at,e2e_run_id:ids.e2eRunId,synthetic_source:'e2e',soft_deleted_at:null},preparationSnapshot:{synthetic:'snapshot'},generatedDraft:{generatedDocumentId:'generated-document:sha256:'+'a'.repeat(64),generatedPdfSha256:'b'.repeat(64),generatedByteLength:3},generatedDraftBytes:Uint8Array.from([1,2,3]),currentnessMaterialBinding:{schemaVersion:1,officialSourceHealth:'CURRENT'},renderedAcknowledgmentTemplate:{renderedGeneratedDocumentId:'generated-document:sha256:'+'a'.repeat(64),renderedPdfSha256:'b'.repeat(64),renderedByteLength:3},reviewStatement:{statementId:'owner-exact-rendered-document-review-v1',statementVersion:'1.0.0'}};}

type Opt={authUserId?:string|null;authError?:unknown;authThrows?:boolean;initialRow?:unknown;readError?:boolean;insertMode?:'success'|'conflict'|'error';materializeThrows?:boolean};
function harness(o:Opt={}){const preview=createSyntheticQualificationPreview();let stored=o.initialRow??null,inserts=0,reads=0,mats=0,last:any=null;const q:any={select(){return q},eq(){return q},limit(){return q},async maybeSingle(){reads++;return o.readError?{data:null,error:{message:'read'}}:{data:stored,error:null}},insert(row:any){inserts++;last=row;return {select(){return {async single(){if(o.insertMode==='error')return {data:null,error:{code:'XX000'}};if(o.insertMode==='conflict'){stored=structuredClone(row);return {data:null,error:{code:'23505'}}}stored=structuredClone(row);return {data:{id:row.id},error:null}}}}}}};const client:any={auth:{async getUser(){if(o.authThrows)throw new Error('auth');return {data:{user:o.authUserId===null?null:{id:o.authUserId??USER}},error:o.authError??null}}},from(t:string){assert.equal(t,'riskpath_records');return q}};const d:SyntheticBootstrapRouteDependencies={createUserScopedClient(){return client},nowISO(){return AT},createPreview(){return preview},async materialize(i){mats++;if(o.materializeThrows)throw new Error('blocked');return fake(i.authenticatedUserId,i.reviewApprovalGeneration,i.ceremonyAtISO)}};return {d,preview,getRow:()=>stored,getInserts:()=>inserts,getReads:()=>reads,getMats:()=>mats,getLast:()=>last};}

(async()=>{
  const missing=harness();const noAuth=new Request('https://ownerpilot.test/bootstrap',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'PREVIEW'})});eq((await handleSyntheticBootstrapRequest(noAuth,missing.d)).status,401,'missing bearer blocked');eq(missing.getInserts(),0,'no auth no write');
  for(const h of ['Basic abc','Bearer','Bearer ','Bearer two tokens']){const x=harness();eq((await handleSyntheticBootstrapRequest(req({action:'PREVIEW'},h),x.d)).status,401,`malformed ${h} blocked`);eq(x.getInserts(),0,'malformed auth no write');}
  for(const x of [harness({authUserId:null}),harness({authUserId:'bad'}),harness({authError:{message:'bad'}}),harness({authThrows:true})]){eq((await handleSyntheticBootstrapRequest(req({action:'PREVIEW'}),x.d)).status,401,'auth.getUser failure blocked');eq(x.getInserts(),0,'failed user auth no write');}

  const pv=harness();const pr=await handleSyntheticBootstrapRequest(req({action:'PREVIEW'}),pv.d);eq(pr.status,200,'PREVIEW succeeds');eq((await body(pr)).status,'PREVIEW_READY','bounded PREVIEW response');eq(pv.getReads(),0,'PREVIEW no durable read');eq(pv.getInserts(),0,'PREVIEW zero writes');eq(pv.getMats(),0,'PREVIEW no governed materialization');
  const inj=harness();eq((await handleSyntheticBootstrapRequest(req({action:'PREVIEW',riskpathRecordId:'caller'}),inj.d)).status,400,'PREVIEW target injection rejected');eq(inj.getInserts(),0,'injected PREVIEW no write');

  const commit=(p:any)=>({action:'COMMIT',reviewApprovalGeneration:p.reviewApprovalGeneration,createReviewConfirmed:true,fixedElectionProfileConfirmed:true});
  for(const b of [{...commit(pv.preview),createReviewConfirmed:false},{...commit(pv.preview),fixedElectionProfileConfirmed:false}]){const x=harness();eq((await handleSyntheticBootstrapRequest(req(b),x.d)).status,400,'literal human confirmation required');eq(x.getInserts(),0,'missing confirmation no write');}
  const authority=harness();eq((await handleSyntheticBootstrapRequest(req({...commit(authority.preview),governedControls:{}}),authority.d)).status,400,'caller authority injection rejected');eq(authority.getInserts(),0,'authority injection no write');
  const tamper=harness();eq((await handleSyntheticBootstrapRequest(req({...commit(tamper.preview),reviewApprovalGeneration:tamper.preview.reviewApprovalGeneration+'x'}),tamper.d)).status,409,'tampered preview generation blocked');eq(tamper.getMats(),0,'tamper blocks before materialization');eq(tamper.getInserts(),0,'tamper blocks before write');

  const first=harness();const fr=await handleSyntheticBootstrapRequest(req(commit(first.preview)),first.d);eq(fr.status,200,'first COMMIT succeeds');eq((await body(fr)).disposition,'INSERTED','first COMMIT inserted');eq(first.getInserts(),1,'exactly one INSERT');eq(first.getMats(),1,'materialized once');ok(first.getReads()>=2,'absence check plus round-trip read');const row=first.getLast();eq(row.user_id,USER,'owner from auth only');eq(row.synthetic_source,'e2e','server synthetic tag');eq(row.chat_session_id,null,'no chat linkage');eq(row.property_id,null,'no property linkage');eq(row.notice_document_id,null,'no document linkage');eq(row.produce_snapshot.producedAtISO,AT,'server ceremony bound');
  const retry=harness({initialRow:first.getRow()});const rr=await handleSyntheticBootstrapRequest(req(commit(retry.preview)),retry.d);eq(rr.status,200,'identical retry succeeds');eq((await body(rr)).disposition,'IDEMPOTENT_EXISTING','retry exact existing');eq(retry.getInserts(),0,'retry no second insert');eq(retry.getMats(),1,'retry rematerializes only for reconciliation');
  const bad=structuredClone(first.getRow()) as any;bad.e2e_run_id='33333333-3333-4333-8333-333333333333';const collision=harness({initialRow:bad});eq((await handleSyntheticBootstrapRequest(req(commit(collision.preview)),collision.d)).status,409,'mismatched deterministic collision blocked');eq(collision.getInserts(),0,'collision no mutation');
  const race=harness({insertMode:'conflict'});const raceR=await handleSyntheticBootstrapRequest(req(commit(race.preview)),race.d);eq(raceR.status,200,'identical concurrent winner reconciles');eq((await body(raceR)).disposition,'IDEMPOTENT_EXISTING','race exact existing');eq(race.getInserts(),1,'race at most one insert');
  const readFail=harness({readError:true});eq((await handleSyntheticBootstrapRequest(req(commit(readFail.preview)),readFail.d)).status,503,'read infrastructure fails closed');eq(readFail.getInserts(),0,'read failure no write');
  const genFail=harness({materializeThrows:true});eq((await handleSyntheticBootstrapRequest(req(commit(genFail.preview)),genFail.d)).status,409,'canonical materialization failure blocked');eq(genFail.getInserts(),0,'generation failure no target');
  const writeFail=harness({insertMode:'error'});eq((await handleSyntheticBootstrapRequest(req(commit(writeFail.preview)),writeFail.d)).status,503,'write failure surfaced');eq(writeFail.getInserts(),1,'write failure no retry insert');

  const src=readFileSync('app/api/riskpath/filing-preparation/synthetic-qualification/bootstrap/route.ts','utf8');eq((src.match(/\.insert\(/g)??[]).length,1,'exactly one insert primitive');ok(src.includes("from('riskpath_records')"),'only authorized table');ok(!src.includes('.update(')&&!src.includes('.upsert(')&&!src.includes('.delete('),'no update/upsert/delete/retag');ok(!src.includes('service_events')&&!src.includes('service_evidence_assets'),'no ordinary service writes');ok(!/service[_-]?role/i.test(src),'no service-role credential path');ok(!src.includes('refresh_token')&&!src.includes('access_token'),'no token return fields');
  console.log(`synthetic bootstrap route: ${passed} assertions passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
