#!/usr/bin/env node
/**
 * constitution/tools/dump_constitution.mjs — portable constitution-schema DDL dumper.
 *
 * Produces a faithful, re-applyable schema-only dump of the `constitution` schema WITHOUT pg_dump / Docker / brew —
 * only the pure-JS `pg` driver. Reusable for every baseline refresh (workflow step 8).
 *
 * Usage:
 *   npm i pg --no-save                 # pure-JS Postgres driver; --no-save keeps package.json clean
 *   CONN="postgresql://postgres:PW@db.txpetdrfsmqnyooydmas.supabase.co:5432/postgres" \
 *     node constitution/tools/dump_constitution.mjs
 *   # (writes constitution/baseline/constitution_v1.0.sql; pass a different path as argv[2] if desired)
 *
 * Emits, in dependency-safe order: CREATE TABLE (cols + inline PK/UNIQUE/CHECK) → ALTER TABLE ADD FK →
 *   ENABLE RLS → CREATE INDEX (non-constraint) → functions → triggers → comments. FK constraints are emitted
 *   after all tables so ordering never breaks. Exact DDL for functions/triggers/indexes/constraints comes from
 *   the pg_get_*def catalog functions (byte-faithful); tables are reconstructed from pg_catalog.
 */

import { writeFileSync } from 'node:fs';

const CONN = process.env.CONN || process.argv[3];
const OUT = process.argv[2] || 'constitution/baseline/constitution_v1.0.sql';
// Two ways to authenticate: (a) CONN = full URI, or (b) discrete PG* env vars (PGHOST/PGPORT/PGUSER/PGPASSWORD/
// PGDATABASE) — preferred when the password has special characters, since PGPASSWORD is taken literally (no URI
// percent-encoding). pg reads the PG* vars automatically when no connectionString is given.
if (!CONN && !process.env.PGHOST) {
  console.error('Set CONN (full URI) OR the PG* env vars (PGHOST, PGUSER, PGPASSWORD, PGDATABASE, PGPORT).');
  process.exit(2);
}

let pg;
try { pg = (await import('pg')).default; }
catch { console.error('Missing `pg`. Run:  npm i pg --no-save'); process.exit(2); }

const client = new pg.Client(
  CONN
    ? { connectionString: CONN, application_name: 'constitution_dump', ssl: { rejectUnauthorized: false } }
    : { application_name: 'constitution_dump', ssl: { rejectUnauthorized: false } }); // PG* env vars
const q = async (sql, params) => (await client.query(sql, params)).rows;
const sq = (s) => s.replace(/'/g, "''"); // single-quote escape for comment literals

try {
  await client.connect();
  const out = [];
  out.push('-- constitution_v1.0.sql — Constitution schema baseline (schema-only).');
  out.push('-- Generated by constitution/tools/dump_constitution.mjs. Do not hand-edit; regenerate on baseline refresh.');
  out.push(`-- Generated: ${new Date().toISOString()}`);
  out.push('');
  out.push('create schema if not exists constitution;');
  out.push('');

  const tables = await q(
    `select c.oid, c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='constitution' and c.relkind='r' order by c.relname`);

  const deferredFks = [];
  for (const t of tables) {
    const cols = await q(
      `select a.attname, format_type(a.atttypid,a.atttypmod) typ, a.attnotnull nn, pg_get_expr(ad.adbin,ad.adrelid) def
       from pg_attribute a left join pg_attrdef ad on ad.adrelid=a.attrelid and ad.adnum=a.attnum
       where a.attrelid=$1 and a.attnum>0 and not a.attisdropped order by a.attnum`, [t.oid]);
    const cons = await q(
      `select conname, contype, pg_get_constraintdef(oid) def from pg_constraint where conrelid=$1 order by contype, conname`, [t.oid]);

    const lines = cols.map((c) =>
      `  ${c.attname} ${c.typ}${c.nn ? ' not null' : ''}${c.def != null ? ' default ' + c.def : ''}`);
    for (const c of cons) {
      if (c.contype === 'f') { deferredFks.push(`alter table constitution.${t.relname} add constraint ${c.conname} ${c.def};`); continue; }
      lines.push(`  constraint ${c.conname} ${c.def}`);
    }
    out.push(`create table constitution.${t.relname} (\n${lines.join(',\n')}\n);`);
  }
  out.push('');

  if (deferredFks.length) { out.push('-- Foreign keys'); out.push(...deferredFks); out.push(''); }

  out.push('-- Row Level Security (deny-by-default: enabled, no policies)');
  for (const t of tables) out.push(`alter table constitution.${t.relname} enable row level security;`);
  out.push('');

  const idx = await q(
    `select pg_get_indexdef(i.indexrelid) def from pg_index i join pg_class c on c.oid=i.indrelid join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='constitution' and not exists (select 1 from pg_constraint con where con.conindid=i.indexrelid)
     order by pg_get_indexdef(i.indexrelid)`);
  if (idx.length) { out.push('-- Indexes (non-constraint)'); out.push(...idx.map((r) => r.def + ';')); out.push(''); }

  const fns = await q(
    `select pg_get_functiondef(p.oid) def from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='constitution' order by p.proname`);
  if (fns.length) { out.push('-- Functions'); out.push(...fns.map((r) => r.def.trimEnd() + ';')); out.push(''); }

  const trg = await q(
    `select pg_get_triggerdef(t.oid) def from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='constitution' and not t.tgisinternal order by c.relname, t.tgname`);
  if (trg.length) { out.push('-- Triggers'); out.push(...trg.map((r) => r.def + ';')); out.push(''); }

  const tc = await q(
    `select c.relname, obj_description(c.oid,'pg_class') cmt from pg_class c join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='constitution' and c.relkind='r' and obj_description(c.oid,'pg_class') is not null order by c.relname`);
  const cc = await q(
    `select c.relname, a.attname, col_description(c.oid,a.attnum) cmt from pg_class c join pg_namespace n on n.oid=c.relnamespace
     join pg_attribute a on a.attrelid=c.oid where n.nspname='constitution' and c.relkind='r' and a.attnum>0 and not a.attisdropped
     and col_description(c.oid,a.attnum) is not null order by c.relname, a.attnum`);
  if (tc.length || cc.length) {
    out.push('-- Comments');
    for (const r of tc) out.push(`comment on table constitution.${r.relname} is '${sq(r.cmt)}';`);
    for (const r of cc) out.push(`comment on column constitution.${r.relname}.${r.attname} is '${sq(r.cmt)}';`);
    out.push('');
  }

  writeFileSync(OUT, out.join('\n') + '\n');
  console.log(`Wrote ${OUT} — ${tables.length} tables, ${deferredFks.length} FKs, ${idx.length} indexes, ${fns.length} functions, ${trg.length} triggers.`);
} catch (e) {
  console.error('dump failed:', e instanceof Error ? e.message : e);
  process.exitCode = 1;
} finally {
  await client.end().catch(() => {});
}
