import { strict as assert } from 'node:assert';
import {
  LASC_CIV_312_FIELD_MAP_ID,LASC_CIV_312_FIELD_MAP_SNAPSHOT,LASC_CIV_312_FIELD_MAP_VERSION,LASC_CIV_312_FORM_ID,LASC_CIV_312_FORM_REVISION,LASC_CIV_312_SOURCE_SHA256,LASC_CIV_312_TERMINAL_FIELDS,
} from './lascCiv312FieldMapFoundation';
import {
  LASC_CIV_312_GENERATION_BINDING_PROFILE_ID,LASC_CIV_312_GENERATION_BINDING_PROFILE_SNAPSHOT,LASC_CIV_312_GENERATION_BINDING_PROFILE_VERSION,LASC_CIV_312_GOVERNANCE_POSTURE,
  type LascCiv312GenerationBindingResult,
} from './lascCiv312GenerationBinding';
import {
  OFFICIAL_FORM_GENERATED_DRAFT_ADMISSION_GOVERNANCE,computeOfficialFormPreparationAuthorizationSnapshot,type OfficialFormPreparationRelevanceAuthorization,
} from './officialFormGeneratedDraftAdmission';
import {
  LASC_CIV_312_EXPECTED_PAGE_COUNT,LASC_CIV_312_EXPECTED_TERMINAL_FIELD_COUNT,LASC_CIV_312_GENERATED_DRAFT_ADMISSION_PROFILE_ID,LASC_CIV_312_GENERATED_DRAFT_ADMISSION_PROFILE_SNAPSHOT,LASC_CIV_312_GENERATED_DRAFT_ADMISSION_PROFILE_VERSION,LASC_CIV_312_GENERATED_DRAFT_TARGET,computeLascCiv312GeneratedDraftAdmissionProfileSnapshot,evaluateLascCiv312GeneratedDraftAdmission,
} from './lascCiv312GeneratedDraftAdmission';

let passed=0; const ok=(v:unknown,m:string)=>{assert.ok(v,m);passed+=1}; const equal=<T>(a:T,e:T,m:string)=>{assert.equal(a,e,m);passed+=1}; const notEqual=<T>(a:T,e:T,m:string)=>{assert.notEqual(a,e,m);passed+=1}; const deepEqual=(a:unknown,e:unknown,m:string)=>{assert.deepEqual(a,e,m);passed+=1};
const context={generation:'synthetic-generation-1',createdAtISO:'2026-09-01T00:00:00.000Z'};
const defendantProv={createdNotice:context,sourcePaths:['createData.tenantNames'],provenanceClass:'FROZEN_CUSTOMER_CONFIRMED',dependencies:[]};
const phoneProv=(i:number)=>({createdNotice:context,sourcePaths:[`supplemental.defendantTelephones[${i}]`],provenanceClass:'SUPPLEMENTAL_CUSTOMER_INPUT',dependencies:[]});
const plaintiffProv={createdNotice:context,sourcePaths:['createData.landlordIdentity'],provenanceClass:'DETERMINISTIC_DERIVATION',dependencies:['landlord.identity']};
const protectedDestinations=LASC_CIV_312_TERMINAL_FIELDS.filter(f=>f.classification==='PROTECTED_NO_WRITE').map(f=>({fieldId:f.fieldId,reason:f.noWriteReason!}));
function ready():Extract<LascCiv312GenerationBindingResult,{status:'GENERATION_BINDING_READY'}>{return {status:'GENERATION_BINDING_READY',formId:LASC_CIV_312_FORM_ID,formRevision:LASC_CIV_312_FORM_REVISION,sourceSha256:LASC_CIV_312_SOURCE_SHA256,fieldMapId:LASC_CIV_312_FIELD_MAP_ID,fieldMapVersion:LASC_CIV_312_FIELD_MAP_VERSION,fieldMapSnapshot:LASC_CIV_312_FIELD_MAP_SNAPSHOT,generationBindingProfileId:LASC_CIV_312_GENERATION_BINDING_PROFILE_ID,generationBindingProfileVersion:LASC_CIV_312_GENERATION_BINDING_PROFILE_VERSION,generationBindingProfileSnapshot:LASC_CIV_312_GENERATION_BINDING_PROFILE_SNAPSHOT,fieldWritePlan:[
{action:'WRITE_TEXT',fieldId:'Defendant Name 1',value:'Synthetic Tenant One',canonicalFactRef:'defendant.names',provenance:defendantProv},
{action:'WRITE_TEXT',fieldId:'Cellular Telephone 1',value:'555-0101',canonicalFactRef:'defendant.0.telephone',provenance:phoneProv(0)},
{action:'WRITE_TEXT',fieldId:'Defendant Name 2',value:'Synthetic Tenant Two',canonicalFactRef:'defendant.names',provenance:defendantProv},
{action:'WRITE_TEXT',fieldId:'Cellular Telephone 2',value:'555-0102',canonicalFactRef:'defendant.1.telephone',provenance:phoneProv(1)},
{action:'WRITE_TEXT',fieldId:'Plaintiff Name 1',value:'Synthetic Owner LLC',canonicalFactRef:'plaintiff.names',provenance:plaintiffProv},
],protectedDestinations,governance:LASC_CIV_312_GOVERNANCE_POSTURE};}
function auth(overrides:Partial<OfficialFormPreparationRelevanceAuthorization>={}):OfficialFormPreparationRelevanceAuthorization{const base:any={authorizationId:'synthetic-auth-1',resultId:'synthetic-result-1',controlId:'civ312-preparation-relevance',controlVersion:'v1',status:'CURRENT',decision:'FORM_RELEVANT_FOR_PREPARATION',target:LASC_CIV_312_GENERATED_DRAFT_TARGET,matterContextIdentity:context,...overrides}; if(!overrides.authorizationSnapshot)base.authorizationSnapshot=computeOfficialFormPreparationAuthorizationSnapshot({authorizationId:base.authorizationId,resultId:base.resultId,controlId:base.controlId,controlVersion:base.controlVersion,status:base.status,decision:base.decision,target:base.target,matterContextIdentity:base.matterContextIdentity});return base;}

equal(LASC_CIV_312_GENERATED_DRAFT_ADMISSION_PROFILE_ID,'lasc-civ312-generated-draft-admission-v1','profile id frozen');
equal(LASC_CIV_312_GENERATED_DRAFT_ADMISSION_PROFILE_VERSION,'2026-09-01.r1','profile version frozen');
equal(LASC_CIV_312_GENERATED_DRAFT_ADMISSION_PROFILE_SNAPSHOT,'sha256:0b00717ee09b9ada93a327fdaf3f354f67f9acf95d91bad4052aa717fc7a2576','profile snapshot frozen');
equal(computeLascCiv312GeneratedDraftAdmissionProfileSnapshot(),LASC_CIV_312_GENERATED_DRAFT_ADMISSION_PROFILE_SNAPSHOT,'profile snapshot deterministic');
equal(LASC_CIV_312_EXPECTED_PAGE_COUNT,1,'expected page count exactly one');
equal(LASC_CIV_312_EXPECTED_TERMINAL_FIELD_COUNT,22,'expected terminal count exactly twenty-two');
equal(LASC_CIV_312_GENERATED_DRAFT_TARGET.formId,'LASC-CIV-312','form identity frozen');
equal(LASC_CIV_312_GENERATED_DRAFT_TARGET.formRevision,'2025-10','revision frozen');
equal(LASC_CIV_312_GENERATED_DRAFT_TARGET.sourceSha256,'f27059765f500b0b62b00b0a382641c80763673233fecd0d4d4a740852c9ae1f','source hash frozen');
equal(LASC_CIV_312_GENERATED_DRAFT_TARGET.fieldMapSnapshot,'sha256:3b578aab3837a2c2968059524db1c4f4923d4829984478cb2ce0117b3e4797b9','map snapshot frozen');
equal(LASC_CIV_312_GENERATED_DRAFT_TARGET.generationBindingProfileSnapshot,'sha256:01e8f4f9cd4d6baf804c8752ab5e1a11c89e4fccf4debdc6ab917abd1f890824','binding profile frozen');

const baseline=evaluateLascCiv312GeneratedDraftAdmission(ready(),auth(),context); equal(baseline.status,'ADMISSION_READY','valid exact D1 plan admitted'); if(baseline.status!=='ADMISSION_READY')throw new Error('baseline');
equal(baseline.completeTerminalPlan.length,22,'normalized plan has exactly 22 destinations');
equal(new Set(baseline.completeTerminalPlan.map(i=>i.fieldId)).size,22,'normalized destinations unique');
deepEqual(baseline.completeTerminalPlan.map(i=>i.fieldId),LASC_CIV_312_TERMINAL_FIELDS.map(f=>f.fieldId),'normalized plan preserves exact authenticated field order');
for(const write of ready().fieldWritePlan){const item=baseline.completeTerminalPlan.find(i=>i.fieldId===write.fieldId);equal(item?.action,'WRITE_TEXT',`${write.fieldId} remains write`);if(item?.action==='WRITE_TEXT'){equal(item.value,write.value,`${write.fieldId} value exact`);equal(item.canonicalFactRef,write.canonicalFactRef,`${write.fieldId} fact ref exact`);deepEqual(item.provenance,write.provenance,`${write.fieldId} provenance exact`);}}
const unused=['Defendant Name 3','Defendant Name 4','Defendant Name 5','Cellular Telephone 3','Cellular Telephone 4','Cellular Telephone 5','Plaintiff Name 2']; for(const id of unused){equal(baseline.completeTerminalPlan.find(i=>i.fieldId===id)?.action,'PRESERVE_OFFICIAL_BLANK_NO_WRITE',`${id} unused slot is no-write`);}
const protectedIds=['COURTHOUSE ADDRESS','PLAINTIFFS','DEFENDANTS','CASE NUMBER','Date','check box','Cellular Telephone 6','Cellular Telephone 7','Print Name','Signature']; for(const id of protectedIds){equal(baseline.completeTerminalPlan.find(i=>i.fieldId===id)?.action,'PRESERVE_OFFICIAL_BLANK_NO_WRITE',`${id} protected no-write`);}
equal(baseline.governance.documentGeneration,'NOT_PERFORMED','document generation not performed'); equal(baseline.governance.pdfMutation,'NOT_PERFORMED','pdf mutation not performed'); equal(baseline.governance.databaseWrite,'NO','db no'); equal(baseline.governance.persistence,'NO','persistence no'); equal(baseline.governance.preparationCheckpointWrite,'NO','prep checkpoint no'); equal(baseline.governance.ownerReviewCheckpointWrite,'NO','owner checkpoint no'); equal(baseline.governance.checkpoint1,'HELD','checkpoint held'); equal(baseline.governance.filing,'NO','filing no'); equal(baseline.governance.signing,'NO','signing no'); equal(baseline.governance.serviceExecution,'NO','service no'); equal(baseline.governance.courtSubmission,'NO','court no'); equal(baseline.governance.stageF,'HELD','stage F held'); equal(baseline.governance.newProductionAuthority,'NO','Production held');
const repeat=evaluateLascCiv312GeneratedDraftAdmission(ready(),auth(),context); equal(repeat.status,'ADMISSION_READY','repeat ready'); if(repeat.status==='ADMISSION_READY'){equal(repeat.completeTerminalPlanSnapshot,baseline.completeTerminalPlanSnapshot,'plan snapshot repeat deterministic');equal(repeat.admissionSnapshot,baseline.admissionSnapshot,'admission snapshot repeat deterministic');}
const changedAuth=evaluateLascCiv312GeneratedDraftAdmission(ready(),auth({resultId:'synthetic-result-2'}),context); equal(changedAuth.status,'ADMISSION_READY','new exact auth still can admit'); if(changedAuth.status==='ADMISSION_READY')notEqual(changedAuth.admissionSnapshot,baseline.admissionSnapshot,'auth identity changes admission snapshot');
const changedContext={...context,generation:'synthetic-generation-2'}; const ctxAuth=auth({matterContextIdentity:changedContext}); const changedContextResult=evaluateLascCiv312GeneratedDraftAdmission(ready(),ctxAuth,changedContext); equal(changedContextResult.status==='BLOCKED'?changedContextResult.blockerCode:'','D1_MATTER_CONTEXT_MISMATCH','wrong D1 Created-Notice context blocks even with matching current authorization');

const blockedD1:LascCiv312GenerationBindingResult={status:'BLOCKED',blockerCode:'UNANSWERED_DEFENDANT_PHONE',reason:'synthetic',fieldWritePlan:[],protectedDestinations,governance:LASC_CIV_312_GOVERNANCE_POSTURE}; const blocked=evaluateLascCiv312GeneratedDraftAdmission(blockedD1,auth(),context); equal(blocked.status==='BLOCKED'?blocked.blockerCode:'','D1_BINDING_BLOCKED','D1 blocked propagates'); equal(blocked.completeTerminalPlan.length,0,'D1 blocked returns no partial plan');
const emptyReady=ready(); (emptyReady as any).fieldWritePlan=[]; const emptyReadyResult=evaluateLascCiv312GeneratedDraftAdmission(emptyReady,auth(),context); equal(emptyReadyResult.status==='BLOCKED'?emptyReadyResult.blockerCode:'','D1_WRITE_PLAN_INVALID','spoofed ready result with zero writes fails closed');
const wrongForm={...ready(),formId:'OTHER' as any}; const wrongFormResult=evaluateLascCiv312GeneratedDraftAdmission(wrongForm,auth(),context); equal(wrongFormResult.status==='BLOCKED'?wrongFormResult.blockerCode:'','D1_IDENTITY_MISMATCH','wrong D1 form blocks');
const wrongRevision={...ready(),formRevision:'OTHER' as any}; equal(evaluateLascCiv312GeneratedDraftAdmission(wrongRevision,auth(),context).status,'BLOCKED','wrong revision blocks');
const wrongSource={...ready(),sourceSha256:'0'.repeat(64) as any}; equal(evaluateLascCiv312GeneratedDraftAdmission(wrongSource,auth(),context).status,'BLOCKED','wrong source blocks');
const wrongMap={...ready(),fieldMapSnapshot:`sha256:${'0'.repeat(64)}`}; equal(evaluateLascCiv312GeneratedDraftAdmission(wrongMap,auth(),context).status,'BLOCKED','wrong map blocks');
const wrongProfile={...ready(),generationBindingProfileSnapshot:`sha256:${'0'.repeat(64)}`}; equal(evaluateLascCiv312GeneratedDraftAdmission(wrongProfile,auth(),context).status,'BLOCKED','wrong binding profile blocks');
const missingAuth=evaluateLascCiv312GeneratedDraftAdmission(ready(),null as any,context); equal(missingAuth.status==='BLOCKED'?missingAuth.blockerCode:'','GENERIC_ADMISSION_BLOCKED','missing auth blocks');
const staleAuth=evaluateLascCiv312GeneratedDraftAdmission(ready(),auth({status:'STALE'}),context); equal(staleAuth.status,'BLOCKED','stale auth blocks');
const notRelevant=evaluateLascCiv312GeneratedDraftAdmission(ready(),auth({decision:'FORM_NOT_RELEVANT_FOR_PREPARATION'}),context); equal(notRelevant.status,'BLOCKED','not relevant auth blocks');
const authWrongForm=evaluateLascCiv312GeneratedDraftAdmission(ready(),auth({target:{...LASC_CIV_312_GENERATED_DRAFT_TARGET,formId:'OTHER'}}),context); equal(authWrongForm.status,'BLOCKED','auth wrong form blocks');
const authWrongRevision=evaluateLascCiv312GeneratedDraftAdmission(ready(),auth({target:{...LASC_CIV_312_GENERATED_DRAFT_TARGET,formRevision:'OTHER'}}),context); equal(authWrongRevision.status,'BLOCKED','auth wrong revision blocks');
const authWrongSource=evaluateLascCiv312GeneratedDraftAdmission(ready(),auth({target:{...LASC_CIV_312_GENERATED_DRAFT_TARGET,sourceSha256:'0'.repeat(64)}}),context); equal(authWrongSource.status,'BLOCKED','auth wrong source blocks');
const authWrongMap=evaluateLascCiv312GeneratedDraftAdmission(ready(),auth({target:{...LASC_CIV_312_GENERATED_DRAFT_TARGET,fieldMapSnapshot:`sha256:${'0'.repeat(64)}`}}),context); equal(authWrongMap.status,'BLOCKED','auth wrong map blocks');
const authWrongProfile=evaluateLascCiv312GeneratedDraftAdmission(ready(),auth({target:{...LASC_CIV_312_GENERATED_DRAFT_TARGET,generationBindingProfileSnapshot:`sha256:${'0'.repeat(64)}`}}),context); equal(authWrongProfile.status,'BLOCKED','auth wrong profile blocks');
const authWrongContext=evaluateLascCiv312GeneratedDraftAdmission(ready(),auth({matterContextIdentity:{...context,generation:'wrong'}}),context); equal(authWrongContext.status,'BLOCKED','auth wrong matter context blocks');
const dupWrites=ready(); (dupWrites.fieldWritePlan as any[]).push(dupWrites.fieldWritePlan[0]); const dupResult=evaluateLascCiv312GeneratedDraftAdmission(dupWrites,auth(),context); equal(dupResult.status==='BLOCKED'?dupResult.blockerCode:'','D1_WRITE_PLAN_INVALID','duplicate D1 destination blocks');
const protectedWrite=ready(); (protectedWrite.fieldWritePlan as any[]).push({action:'WRITE_TEXT',fieldId:'check box',value:'On',canonicalFactRef:'synthetic',provenance:defendantProv}); equal(evaluateLascCiv312GeneratedDraftAdmission(protectedWrite,auth(),context).status,'BLOCKED','protected destination smuggling blocks');
const unexpectedWrite=ready(); (unexpectedWrite.fieldWritePlan as any[]).push({action:'WRITE_TEXT',fieldId:'UNEXPECTED',value:'x',canonicalFactRef:'synthetic',provenance:defendantProv}); equal(evaluateLascCiv312GeneratedDraftAdmission(unexpectedWrite,auth(),context).status,'BLOCKED','unexpected destination blocks');
const badProtected=ready(); (badProtected.protectedDestinations as any[]).pop(); const badProtectedResult=evaluateLascCiv312GeneratedDraftAdmission(badProtected,auth(),context); equal(badProtectedResult.status==='BLOCKED'?badProtectedResult.blockerCode:'','D1_PROTECTED_DESTINATIONS_INVALID','omitted protected destination blocks');
const badGov=ready(); (badGov as any).governance={...LASC_CIV_312_GOVERNANCE_POSTURE,documentGeneration:'PERFORMED'}; const badGovResult=evaluateLascCiv312GeneratedDraftAdmission(badGov,auth(),context); equal(badGovResult.status==='BLOCKED'?badGovResult.blockerCode:'','D1_GOVERNANCE_MISMATCH','performed D1 generation posture blocks');
const byteBearing=ready() as any; byteBearing.pdfBytes=new Uint8Array([1,2,3]); const byteBearingResult=evaluateLascCiv312GeneratedDraftAdmission(byteBearing,auth(),context); equal(byteBearingResult.status==='BLOCKED'?byteBearingResult.blockerCode:'','PDF_BYTES_NOT_ALLOWED','CIV 312 adapter rejects PDF bytes');
ok(!JSON.stringify(baseline).match(/\b\d{3}-\d{3}-\d{4}\b/),'no real-looking ten-digit phone fixture'); ok(baseline.completeTerminalPlan.filter(item=>item.action==='WRITE_TEXT').every(item=>item.action==='WRITE_TEXT' && (item.value.startsWith('Synthetic ') || item.value.startsWith('555-'))),'all emitted fixture values remain synthetic-only'); ok(JSON.stringify(baseline).includes('555-0101'),'synthetic phone retained'); ok(JSON.stringify(baseline).includes('Synthetic Tenant'),'synthetic identities retained');
deepEqual(baseline.governance,OFFICIAL_FORM_GENERATED_DRAFT_ADMISSION_GOVERNANCE,'adapter uses generic no-authority governance');
console.log(`lascCiv312GeneratedDraftAdmission: ${passed} assertions passed`);
