from pathlib import Path

NOTICE = Path('components/notice-flow.tsx')
TEST = Path('lib/flow/noticeReadyTaskBoundary.test.ts')

s = NOTICE.read_text()

summary = "          <ReviewSummaryCards data={data} result={result} goToPage={goToPage} />\n\n"
assert s.count(summary) == 1, f'expected one ReviewSummaryCards placement, got {s.count(summary)}'
s = s.replace(summary, '', 1)

preview = '''      {docHtml && !artifactReady && (\n        <section className="space-y-4 rounded-lg border border-rule bg-white px-5 py-4">\n          <div>\n            <h2 className="text-lg font-semibold text-gray-900">Notice preview</h2>\n            <p className="mt-1 text-xs text-gray-500 leading-relaxed">This is a broker-prepared draft for your review. Sign it in ink before serving, and serve it on the date shown. The proof of service is completed after you serve — not before.</p>\n          </div>\n          <NoticePreview html={docHtml} />\n        </section>\n      )}\n\n'''
assert s.count(preview) == 1, f'expected one Notice Preview block, got {s.count(preview)}'
s = s.replace(preview, '', 1)

c6_nested = '''              <div className="mt-4 space-y-3 border-t border-green-200 pt-4">\n                <p className="text-sm font-semibold text-green-900">Review &amp; Confirm</p>\n                <label className="flex items-start gap-2 cursor-pointer">\n                  <input\n                    type="checkbox"\n                    checked={approvalCurrent}\n                    onChange={(e: ChangeEvent<HTMLInputElement>) =>\n                      update(\n                        e.target.checked\n                          ? bindReviewApproval(data, new Date().toISOString())\n                          : clearReviewApproval(),\n                      )\n                    }\n                    className="mt-1"\n                  />\n                  <span className="text-sm text-green-900 leading-relaxed">\n                    By producing this notice, I confirm: the amounts entered are base rent only (no late fees, utilities, or other charges); the tenants and landlord(s) named are correct; and the signer is authorized.\n                  </span>\n                </label>\n                {!approvalCurrent && (\n                  <p className="text-xs text-green-800">\n                    This confirmation applies only to the exact notice details shown now. If a\n                    material detail changes, you&apos;ll confirm the updated notice again.\n                  </p>\n                )}\n              </div>\n'''
assert s.count(c6_nested) == 1, f'expected one nested C6 block, got {s.count(c6_nested)}'
s = s.replace(c6_nested, '', 1)

intro = '''          <StepIntro>\n            Here&apos;s where your notice stands. Review the details, make the one final\n            confirmation, then create your notice.\n          </StepIntro>\n\n'''
assert s.count(intro) == 1, f'expected one Review StepIntro anchor, got {s.count(intro)}'
review_first = '''          <ReviewSummaryCards data={data} result={result} goToPage={goToPage} />\n\n          {docHtml && !artifactReady && (\n            <section className="space-y-4 rounded-lg border border-rule bg-white px-5 py-4">\n              <div>\n                <h2 className="text-lg font-semibold text-gray-900">Notice preview</h2>\n                <p className="mt-1 text-xs text-gray-500 leading-relaxed">This is a broker-prepared draft for your review. Sign it in ink before serving, and serve it on the date shown. The proof of service is completed after you serve — not before.</p>\n              </div>\n              <NoticePreview html={docHtml} />\n            </section>\n          )}\n\n'''
s = s.replace(intro, intro + review_first, 1)

bank_anchor = '''                <BankDepositAttestations data={data} update={update} />\n              </div>\n            )}\n        </>\n'''
assert s.count(bank_anchor) == 1, f'expected one bank/C6 insertion anchor, got {s.count(bank_anchor)}'
c6_standalone = '''                <BankDepositAttestations data={data} update={update} />\n              </div>\n            )}\n\n          {visibleBlockers.length === 0 && (\n            <div className="rounded-lg border border-green-300 bg-green-50 px-5 py-4">\n              <p className="text-sm font-semibold text-green-900">Review &amp; Confirm</p>\n              <label className="mt-3 flex items-start gap-2 cursor-pointer">\n                <input\n                  type="checkbox"\n                  checked={approvalCurrent}\n                  onChange={(e: ChangeEvent<HTMLInputElement>) =>\n                    update(\n                      e.target.checked\n                        ? bindReviewApproval(data, new Date().toISOString())\n                        : clearReviewApproval(),\n                    )\n                  }\n                  className="mt-1"\n                />\n                <span className="text-sm text-green-900 leading-relaxed">\n                  By producing this notice, I confirm: the amounts entered are base rent only (no late fees, utilities, or other charges); the tenants and landlord(s) named are correct; and the signer is authorized.\n                </span>\n              </label>\n              {!approvalCurrent && (\n                <p className="mt-3 text-xs text-green-800">\n                  This confirmation applies only to the exact notice details shown now. If a\n                  material detail changes, you&apos;ll confirm the updated notice again.\n                </p>\n              )}\n            </div>\n          )}\n        </>\n'''
s = s.replace(bank_anchor, c6_standalone, 1)

NOTICE.write_text(s.rstrip() + '\n')

t = TEST.read_text()
test_anchor = '''ok(\n  noticeFlow.includes('Create Notice'),\n  'Create Notice action is customer-visible',\n);\n\n'''
assert t.count(test_anchor) == 1, f'expected one hierarchy-test insertion anchor, got {t.count(test_anchor)}'
order_test = '''const reviewStepStart = noticeFlow.indexOf('function ReviewStep({');\nconst reviewStepEnd = noticeFlow.indexOf('// --- Step 7:', reviewStepStart);\nok(reviewStepStart >= 0 && reviewStepEnd > reviewStepStart, 'ReviewStep source is inspectable');\nconst reviewStepSource = noticeFlow.slice(reviewStepStart, reviewStepEnd);\nconst reviewSummaryIndex = reviewStepSource.indexOf('<ReviewSummaryCards data={data} result={result} goToPage={goToPage} />');\nconst noticePreviewIndex = reviewStepSource.indexOf('<h2 className="text-lg font-semibold text-gray-900">Notice preview</h2>');\nconst c6LabelIndex = reviewStepSource.indexOf('<p className="text-sm font-semibold text-green-900">Review &amp; Confirm</p>');\nconst createNoticeIndex = reviewStepSource.indexOf('data-testid="create-notice-button"');\nok(reviewSummaryIndex >= 0, 'Review Summary remains in the main Review flow');\nok(noticePreviewIndex > reviewSummaryIndex, 'Notice Preview appears after Review Summary');\nok(c6LabelIndex > noticePreviewIndex, 'C6 appears only after Review Summary and Notice Preview');\nok(createNoticeIndex > c6LabelIndex, 'Create Notice appears after the final C6 control');\nequal(\n  (reviewStepSource.match(/checked=\\{approvalCurrent\\}/g) ?? []).length,\n  1,\n  'exactly one consequential C6 checkbox remains',\n);\nequal(\n  (reviewStepSource.match(/By producing this notice, I confirm: the amounts entered are base rent only/g) ?? []).length,\n  1,\n  'C6 substantive testimony is present exactly once',\n);\n\n'''
t = t.replace(test_anchor, test_anchor + order_test, 1)
TEST.write_text(t.rstrip() + '\n')
