-- Historical migration compatibility marker.
-- Version: 20260630162352
-- Historical name: 030_magic_link_tokens
-- Historical SQL is archived outside active migration discovery under supabase/migration-history/application/.
-- Canonical application state is supplied by numeric migration 030_magic_link_tokens.sql.
-- Purpose: represent the retained Production migration-version identity after canonical numeric state exists.
-- No schema-changing SQL is intentionally present in this file.
