create or replace function constitution.build_decision_recommendation(p_experiment_id uuid,p_decision_question text,p_requested_by text default 'Founder') returns uuid language plpgsql security definer set search_path=constitution,public as $$
declare v_request uuid; v_rec uuid; v_candidate uuid; v_name text; v_ev numeric; v_score numeric; v_conf numeric; v_code text; r record;
begin
select sc.id,sc.name,e.expected_value,e.risk_adjusted_score,e.confidence into v_candidate,v_name,v_ev,v_score,v_conf
from constitution.strategy_candidates sc
join lateral (select * from constitution.strategy_simulation_evaluations x where x.experiment_id=p_experiment_id and x.candidate_id=sc.id order by x.created_at desc limit 1) e on true
where sc.experiment_id=p_experiment_id and sc.status in ('champion','eligible','challenger') and coalesce((e.constraint_results->>'passed')::boolean,true)
order by e.risk_adjusted_score desc nulls last,e.confidence desc limit 1;
if v_candidate is null then raise exception 'No constitutionally eligible evaluated candidate'; end if;
v_code:='ESL-006-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS')||'-'||substr(gen_random_uuid()::text,1,8);
insert into constitution.decision_intelligence_requests(request_code,experiment_id,requested_by,decision_question,status) values(replace(v_code,'ESL-006-','DIR-'),p_experiment_id,p_requested_by,p_decision_question,'processing') returning id into v_request;
insert into constitution.decision_recommendations(request_id,experiment_id,selected_candidate_id,recommendation_code,recommendation_status,executive_recommendation,decision_summary,confidence,confidence_band,expected_value,risk_adjusted_score,evidence_strength,uncertainty_summary,approval_status)
values(v_request,p_experiment_id,v_candidate,v_code,'ready','Recommend '||v_name||'. It has the strongest eligible risk-adjusted result and remains subject to Founder approval.',jsonb_build_object('question',p_decision_question,'recommended_option',v_name,'external_execution_authorized',false),coalesce(v_conf,0),case when coalesce(v_conf,0)>=.9 then 'very_high' when coalesce(v_conf,0)>=.75 then 'high' when coalesce(v_conf,0)>=.55 then 'moderate' else 'low' end,v_ev,v_score,coalesce(v_conf,0),jsonb_build_object('residual_uncertainty',1-coalesce(v_conf,0),'recommendation_can_change',true),'pending') returning id into v_rec;
for r in select sc.id,e.expected_value,e.risk_adjusted_score,e.confidence,e.metric_results,e.constraint_results,e.robustness_results,row_number() over(order by case when coalesce((e.constraint_results->>'passed')::boolean,true) then 0 else 1 end,e.risk_adjusted_score desc nulls last,e.confidence desc) rn from constitution.strategy_candidates sc join lateral(select * from constitution.strategy_simulation_evaluations x where x.experiment_id=p_experiment_id and x.candidate_id=sc.id order by x.created_at desc limit 1)e on true where sc.experiment_id=p_experiment_id loop
insert into constitution.decision_option_assessments(recommendation_id,candidate_id,rank,option_status,expected_value,risk_adjusted_score,confidence,strengths,weaknesses,tradeoffs,constraint_findings,why_selected_or_rejected)
values(v_rec,r.id,r.rn,case when not coalesce((r.constraint_results->>'passed')::boolean,true) then 'ineligible' when r.id=v_candidate then 'recommended' else 'alternative' end,r.expected_value,r.risk_adjusted_score,r.confidence,jsonb_build_array(jsonb_build_object('risk_adjusted_score',r.risk_adjusted_score),jsonb_build_object('confidence',r.confidence)),case when not coalesce((r.constraint_results->>'passed')::boolean,true) then jsonb_build_array(r.constraint_results) else '[]'::jsonb end,jsonb_build_object('metrics',r.metric_results,'robustness',r.robustness_results),r.constraint_results,case when r.id=v_candidate then 'Highest eligible risk-adjusted score.' when not coalesce((r.constraint_results->>'passed')::boolean,true) then 'Failed a hard constraint.' else 'Eligible but ranked below the recommendation.' end);
end loop;
insert into constitution.decision_explanation_factors(recommendation_id,factor_type,factor_name,direction,importance,explanation,evidence_refs,uncertainty) values
(v_rec,'objective','Risk-adjusted performance','supports',.95,'The selected option ranked first among eligible candidates.',jsonb_build_array(jsonb_build_object('candidate_id',v_candidate,'score',v_score)),1-coalesce(v_conf,0)),
(v_rec,'constraint','Constitutional eligibility','supports',1,'Strategies failing hard constraints were excluded.','[]'::jsonb,0),
(v_rec,'dissent','Alternatives remain viable','conditional',.55,'A lower-ranked option may become preferable if assumptions or objective weights change.','[]'::jsonb,.45);
insert into constitution.decision_sensitivity_findings(recommendation_id,variable_name,baseline_value,tested_range,impact_score,switch_threshold,would_change_recommendation,explanation)
select v_rec,key,value,jsonb_build_object('source','objective_weights'),least(1,greatest(0,coalesce((value#>>'{}')::numeric,0))),jsonb_build_object('status','counterfactual_rescoring_required'),true,'Changing this objective weight may alter the ranking.' from constitution.strategy_evolution_experiments e,lateral jsonb_each(e.objective_weights) where e.id=p_experiment_id;
insert into constitution.decision_explainability_audit(recommendation_id,event_type,actor,event_payload) values(v_rec,'recommendation_built',p_requested_by,jsonb_build_object('experiment_id',p_experiment_id,'selected_candidate_id',v_candidate,'approval_required',true));
update constitution.decision_intelligence_requests set status='awaiting_approval',updated_at=now() where id=v_request;
return v_rec;
end $$;