-- Historical migration compatibility marker.
-- Version: 20260630162307
-- Historical name: 026_chat_sessions
-- Historical SQL is archived outside active migration discovery under supabase/migration-history/application/.
-- Canonical application state is supplied by numeric migration 026_chat_sessions.sql.
-- Purpose: represent the retained Production migration-version identity after canonical numeric state exists.
-- No schema-changing SQL is intentionally present in this file.
