-- Historical migration compatibility marker.
-- Version: 20260627194655
-- Historical name: city_zip_refresh_cron
-- Historical SQL is archived outside active migration discovery under supabase/migration-history/application/.
-- Canonical application state is supplied by numeric migration 022_city_zip_refresh_cron.sql.
-- Purpose: represent the retained Production migration-version identity after canonical numeric state exists.
-- No schema-changing SQL is intentionally present in this file.
