-- Historical migration compatibility marker.
-- Version: 20260630174500
-- Historical name: 032_privacy_requests
-- Historical SQL is archived outside active migration discovery under supabase/migration-history/application/.
-- Canonical application state is supplied by numeric migration 032_privacy_requests.sql.
-- Purpose: represent the retained Production migration-version identity after canonical numeric state exists.
-- No schema-changing SQL is intentionally present in this file.
