-- Historical migration compatibility marker.
-- Version: 20260630163312
-- Historical name: 025_broker_confirm_attestation_lookup
-- Historical SQL is archived outside active migration discovery under supabase/migration-history/application/.
-- Canonical application state is supplied by numeric migration 025_broker_confirm_attestation_lookup.sql.
-- Purpose: represent the retained Production migration-version identity after canonical numeric state exists.
-- No schema-changing SQL is intentionally present in this file.
