-- Historical migration compatibility marker.
-- Version: 20260630174444
-- Historical name: 031_chat_sessions_counsel_trigger
-- Historical SQL is archived outside active migration discovery under supabase/migration-history/application/.
-- Canonical application state is supplied by numeric migration 031_chat_sessions_counsel_trigger.sql.
-- Purpose: represent the retained Production migration-version identity after canonical numeric state exists.
-- No schema-changing SQL is intentionally present in this file.
