-- Historical migration compatibility marker.
-- Version: 20260701130402
-- Historical name: 036_lahd_filing_records
-- Production migration history retains this version but its statements column is NULL; no exact historical SQL is recoverable from the ledger.
-- Historical SQL provenance archive: supabase/migration-history/application/UNRECOVERABLE_LEDGER_STATEMENTS.md records this unrecoverable ledger gap; it does not infer missing SQL.
-- Canonical application state is supplied by numeric migration 036_lahd_filing_records.sql.
-- Purpose: represent the retained Production migration-version identity after canonical numeric state exists.
-- No schema-changing SQL is intentionally present in this file.
